import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Sparkles, Play, Award, BarChart3, ArrowRight } from 'lucide-react';

export const AnalyticsEmptyState: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-8 sm:p-12 text-center max-w-2xl mx-auto space-y-6 shadow-xl">
      <div className="w-16 h-16 rounded-2xl bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 flex items-center justify-center mx-auto shadow-inner">
        <BarChart3 className="w-8 h-8" />
      </div>

      <div className="space-y-2">
        <h2 className="text-2xl font-bold text-white tracking-tight">
          No completed interviews yet
        </h2>
        <p className="text-slate-400 text-sm max-w-md mx-auto leading-relaxed">
          Complete your first AI coding interview to unlock comprehensive performance analytics, topic strengths & weaknesses, and a personalized Gemini study roadmap.
        </p>
      </div>

      {/* Feature perks preview */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-left pt-2">
        <div className="p-3.5 bg-slate-950/70 border border-slate-800 rounded-xl space-y-1">
          <div className="text-xs font-semibold text-cyan-400">Score Tracking</div>
          <div className="text-[11px] text-slate-400">Measure trajectory and Big-O complexity mastery.</div>
        </div>
        <div className="p-3.5 bg-slate-950/70 border border-slate-800 rounded-xl space-y-1">
          <div className="text-xs font-semibold text-emerald-400">Topic Diagnosis</div>
          <div className="text-[11px] text-slate-400">Pinpoint your strongest and weakest algorithms.</div>
        </div>
        <div className="p-3.5 bg-slate-950/70 border border-slate-800 rounded-xl space-y-1">
          <div className="text-xs font-semibold text-amber-400">AI Action Plan</div>
          <div className="text-[11px] text-slate-400">Personalized drills generated by Gemini.</div>
        </div>
      </div>

      <div className="pt-4">
        <button
          onClick={() => navigate('/interviews')}
          className="px-6 py-3 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-semibold text-sm transition shadow-lg shadow-cyan-500/20 inline-flex items-center gap-2"
        >
          <Play className="w-4 h-4 fill-current" />
          <span>Start Your First Interview</span>
          <ArrowRight className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
};
